CREATE TABLE IF NOT EXISTS items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  store VARCHAR(255) NULL,
  warranty_months INT NULL,
  article_no VARCHAR(255) NULL,
  purchase_date DATE NULL,
  notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id INT NOT NULL,
  filename VARCHAR(512) NOT NULL,
  original_name VARCHAR(512) NULL,
  mime_type VARCHAR(128) NULL,
  size_bytes BIGINT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);
